package:
  name: hmcnc
  version: 1.0

source:
  path: hmcnc

build:
  number: 1

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - boost
    - htslib
  host:
    - boost
    - htslib
    - zlib
  run:
    - boost
    - htslib

test:
  commands:
    - hmmcnc --help | grep 'Usage'

about:
  home: https://github.com/ChaissonLab/hmcnc/tree/ef8ae26e72830ed7433b8c14ffd2158f7c5ccb9e
  summary: Hidden Markov Copy Number Caller

extra:
  built_for: https://github.com/ChaissonLab/SegDupAnnotation2