# configuration of display in snakemake workflow catalog: https://snakemake.github.io/snakemake-workflow-catalog

usage:
  software-stack-deployment:
    conda: true
    singularity: false
    singularity+conda: true
  report: false
